apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-vol
spec:
  capacity:
    storage: {{ custom_nfs_storage_capacity }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: {{ custom_nfs_server }}
    path: {{ custom_nfs_path }}